matrix:
  include:
    - language: python
      dist: xenial
      node_js: lts/*
      python: 3.7
      cache:
        directories:
          - src/web/node_modules
          - src/api/node_modules
      install:
        # use smaller pytorch version for ci testing
        # per https://github.com/pytorch/pytorch/issues/4178#issuecomment-356709106
        - pip install --progress-bar off -- https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp37-cp37m-linux_x86_64.whl
        - cd src/api && yarn && cd ../../
        - cd src/web && yarn && cd ../../
      script:
        - python3 build.py test all

notifications:
  slack:
    on_success: always
    on_failure: always
    on_pull_requests: false
    rooms:
      - csci3308team1:FGvNcChqAkX2WW8xvD5Z5gvQ#ci-server
