matrix:
  include:
    - language: python
      dist: xenial
      node_js: 10.15.3
      python: 3.7
      cache:
        pip: true
        directories:
          - src/web/node_modules
          - src/api/node_modules
          - ./node_modules
      install:
        - nvm use 10.15.3 && yarn && ./setup.sh
      script:
        - python src/ml/ml_utils_test.py && yarn test

notifications:
  slack:
    on_success: false
    on_failure: always
    on_pull_requests: false
    rooms:
      - csci3308team1:FGvNcChqAkX2WW8xvD5Z5gvQ#ci-server
