

matrix:
  include:
    - language: python
      dist: xenial
      python: 3.7
      script:
        - ./build.py test ml,api
    - language: node_js
      node_js: 11.10
      cache: src/mobile/node_modules
      before_install:
        - cd ./src/mobile
      install:
        - npm i
      before_script:
        - cd ../../
      script:
        - ./src/mobile/node_modules/.bin/jest
notifications:
  # email:
    # - yourname@gmail.com
  slack:
    rooms:
      - csci3308team1:"FGvNcChqAkX2WW8xvD5Z5gvQ"#ci-server
# env:
#   - DB=postgres
#   - SH=bash
#   - PACKAGE_VERSION="1.0.*"
