matrix:
  include:
    - language: python
      dist: xenial
      node_js: lts/*
      python: 3.7
      cache:
        - yarn
        - pip
      install:
        - pip install --user torch
        - cd src/api && yarn && cd ../../
        - cd src/web && yarn && cd ../../
      script:
        - python3 build.py test all

    #   - language: python
    #     dist: xenial
    #     python: 3.7
    #     cache: pip
    #     install:
    #       - pip install torch
    #     script:
    #       - ./build.py test ml,api
    #
    # - language: node_js
    #   node_js: lts/*
    #   cache: yarn
    #   before_install:
    #     - cd src/api
    #   install:
    #     - yarn install
    #   script:
    #     - yarn test --no-watch

notifications:
  slack:
    on_success: always
    on_failure: always
    on_pull_requests: false
    rooms:
      - csci3308team1:FGvNcChqAkX2WW8xvD5Z5gvQ#ci-server
