matrix:
  include:
    - language: python
      dist: xenial
      python: 3.7
      cache: pip
      install:
        - pip install torch numpy matplotlib pandas
      script:
        - ./build.py test ml,api

    - language: node_js
      node_js: 11.10
      cache: yarn
      before_install:
        - cd src/mobile
      install:
        - yarn install
      script:
        - jest

notifications:
  slack:
    on_success: always
    on_failure: always
    on_pull_requests: false
    rooms:
      - csci3308team1:FGvNcChqAkX2WW8xvD5Z5gvQ#ci-server
