matrix:
  include:
    - language: python
      dist: xenial
      node_js: lts/*
      python: 3.7
      cache:
        directories:
          - src/web/node_modules
          - src/api/node_modules
      install:
        - . setup.sh
      script:
        - python3 build.py test all

notifications:
  slack:
    on_success: always
    on_failure: always
    on_pull_requests: false
    rooms:
      - csci3308team1:FGvNcChqAkX2WW8xvD5Z5gvQ#ci-server
